version: "3"

services:
  samba:
    container_name: samba
    image: dperson/samba:latest
    ports:
      - "139:139"
      - "445:445"
    #volumes:
    #  - '/opt/docker/pihole/etc-pihole/:/etc/pihole/'
    restart: unless-stopped
