version: '3.3'
services:
    sonarqube:
        container_name: sonarqube
        ports:
            - '9001:9000'
        image: 'sonarqube:latest'
#        network_mode: host
#        restart: always
