version: "2"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM=claim-L9HzjUX4byPTPu7vwzbd
    volumes:
      #- /path/to/library:/config
      #- path/to/tvseries:/tv
      - /run/media/jorge/JF_01TB/movies/:/movies
    restart: unless-stopped